-- 유저 테이블
create table USERS (  
    USER_ID number not null constraint users_pk primary key,  
    NICKNAME varchar2(50) not null,  
    SIGN_IN_DATE date default sysdate,  
    PROFILE_PHOTO varchar2(1000) not null,  
    EMAIL varchar2(500) NOT NULL,  
    LAST_NAME varchar2(50),    
    FIRST_NAME varchar2(50),
    PIXELS number default 0,  
    ACCUMULATEDPIXELS varchar2(4000) default 0
);
alter table USERS add constraint users_nickname_uq unique (NICKNAME);
alter table USERS add constraint users_profile_photo_uq unique (PROFILE_PHOTO);
alter table USERS add constraint users_email_uq unique (EMAIL);

-- 피드 테이블
CREATE TABLE FEEDS(
	FEED_ID NUMBER PRIMARY KEY 
	,USER_ID1 NUMBER NOT NULL
	,USER_ID2 NUMBER
	,USER_ID3 NUMBER
	,USER_ID4 NUMBER
	,CONTEXT VARCHAR2(4000) NOT NULL
	,INPUTDATE DATE DEFAULT SYSDATE
);

ALTER TABLE FEEDS ADD CONSTRAINT FEEDS_USER_ID1_FK FOREIGN KEY(USER_ID1) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE FEEDS ADD CONSTRAINT FEEDS_USER_ID2_FK FOREIGN KEY(USER_ID2) REFERENCES USERS(USER_ID);
ALTER TABLE FEEDS ADD CONSTRAINT FEEDS_USER_ID3_FK FOREIGN KEY(USER_ID3) REFERENCES USERS(USER_ID);
ALTER TABLE FEEDS ADD CONSTRAINT FEEDS_USER_ID4_FK FOREIGN KEY(USER_ID4) REFERENCES USERS(USER_ID);

-- 태그 테이블
CREATE TABLE TAGS(
	TAG_NAME VARCHAR2(100) PRIMARY KEY
);

-- 피드별 태그 테이블
CREATE TABLE TAGS_IN_FEED(
    TIF_ID NUMBER PRIMARY KEY
    ,FEED_ID NUMBER NOT NULL
    ,TAG_NAME VARCHAR2(100) NOT NULL
);
ALTER TABLE TAGS_IN_FEED ADD CONSTRAINT TAGS_IN_FEED_FEED_ID_FK FOREIGN KEY(FEED_ID) REFERENCES FEEDS(FEED_ID) ON DELETE CASCADE;
ALTER TABLE TAGS_IN_FEED ADD CONSTRAINT TAGS_IN_FEED_TAG_NAME_FK FOREIGN KEY(TAG_NAME) REFERENCES TAGS(TAG_NAME) ON DELETE CASCADE;
